# Composite action for setting up Node.js environment
# This ensures consistent Node.js and npm setup across all workflows

name: Setup Node.js
description: Set up Node.js with npm caching

inputs:
  node-version:
    description: "Node.js version to use"
    required: false
    default: "20"
  install-dependencies:
    description: "Whether to run npm ci"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "npm"

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: npm ci
